### ISSUE TITLE
page is loading pretty slow...

### ISSUE THREAD

**Issue by KodaCaleb** [KodaCaleb/Project-1#28]
idk why or what we can do to fix this, but for some reason when scrolling down stuff seems to pop in and out like the page is loading slowly. Not sure if this is an issue with API network response time (API Ping) or if its something with the code... Would like a second set of eyes to see if we can increase page response time

**Comment by ChrisGordon888** [comment]
I noticed this as well. When I returned to code after about 10 minutes this morning, more titles appeared, but it might have to do with the fact that we are on the free version. Putting the script tag that holds API info in a different place could help slightly.
